import { EventItem } from './eventTypes';

export const EVENTS_MOCK_DATA: EventItem[] = [
  {
    id:          '1',
    title:       'ADICTO: Berlin Festival',
    dateDisplay: '24.02.2022 – 26.02.2022',
    price:       '€30 – €100',
    location:    'Berlin, Germany',
    tags:        ['Workshop', 'Bachata'],
    isFavourited: true,
    imageUri:    'https://picsum.photos/seed/adicto/140/140',
  },
  {
    id:          '2',
    title:       'Bachata: Open level',
    dateDisplay: '27.02.2022 @8pm',
    price:       '€12',
    location:    'Berlin, Germany',
    tags:        ['Course', 'Bachata'],
    isFavourited: false,
    imageUri:    'https://picsum.photos/seed/bachata/140/140',
  },
  {
    id:          '3',
    title:       'SSD Rovinj 2022',
    dateDisplay: '07.06.2022 – 13.06.2022',
    price:       '€65 – €450',
    location:    'Rovinj, Croatia',
    tags:        ['Festival', 'Bachata'],
    isFavourited: false,
    imageUri:    'https://picsum.photos/seed/rovinj/140/140',
  },
  {
    id:          '4',
    title:       'Berlin Sensual Nights',
    dateDisplay: '29.02.2022 | 21:00 – 04:00',
    price:       '€30 – €100',
    location:    'Berlin, Germany',
    tags:        ['Party', 'Bachata', 'Salsa', 'Kizz'],
    isFavourited: true,
    imageUri:    'https://picsum.photos/seed/sensual/140/140',
  },
  {
    id:          '5',
    title:       'Salsa & Bachata Night',
    dateDisplay: '05.03.2022 | 19:00 – 01:00',
    price:       '€7',
    location:    'Berlin, Germany',
    tags:        ['Course', 'Party', 'Bachata', 'Salsa'],
    isFavourited: false,
    imageUri:    'https://picsum.photos/seed/salsanight/140/140',
  },
  {
    id:          '6',
    title:       'Soda Social Club – Salsa, Bachata, ...',
    dateDisplay: '06.03.2022 | 19:00 – 02:00',
    price:       '€8',
    location:    'Berlin, Germany',
    tags:        ['Party', 'Bachata', 'Salsa', 'Kiz'],
    isFavourited: false,
    imageUri:    'https://picsum.photos/seed/soda/140/140',
  },
];
